### PR TITLE
Edit in README.md

### PR DESCRIPTION
**Pull request by jalpa015**
Added Data source in Readme file.

### CODE REVIEW

**Review by arun-esh — COMMENTED** [review]
Should we move documentation to wiki or separate file?

**Comment by jalpa015** [comment]
Yea, we can have separate file when we have a detailed documentation. We can set a timeline for it as it would take a while to do that.

**Comment by arun-esh** [comment]
> Yea, we can have separate file when we have a detailed documentation. We can set a timeline for it as it would take a while to do that.

For now, Please have one separate file for API documentation.

**Comment by jalpa015** [comment]
Alright.

**Comment by arun-esh** [comment]
> Alright.

I will close this PR for now

**Pull request closed without merging**
